### ISSUE TITLE
packaging 

### ISSUE THREAD

**Issue by abdouaziz** [masakhane-io/masakhanePreprocessor#20]
I have been compiled the package and now you can install with ```pip install masakhane-preprocessor```  . 

But when I try to access the Preprocessor with the following code it still does not work. 

```python
from masakhane-preprocessor import Preprocessor

my_prep = Preprocessor(lang='ig')
```

**Comment by chrisemezue** [comment]
@abdouaziz this is the right way to install it
https://github.com/masakhane-io/masakhanePreprocessor#how-to-use--
